In [2]:
## This script will try to crack the data challenge hosted in our competitor's platform -> Ideatory
import numpy as np
import pandas as pd

import DataProcessing as dp

In [3]:
import xgboost as xgb

In [4]:
##$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$##
'''Here comes the global variables to be used by many functions '''
path_root = '/Users/zhaoqf123/DEXTRA/Competitor/Ideatory/ZS_customer_modeling'
train_file = path_root + '/TrainingData_ZS Customer Modeling Challenge.csv'
test_file = path_root + '/EvaluationData_ZS Customer Modeling Challenge.csv'
train_file_out = train_file[:-4] + '_clean.csv'
test_file_out = test_file[:-4] + '_clean.csv'
output_file = path_root + '/Sumission.csv'
##$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$##

In [5]:
df = pd.read_csv(train_file)
df_test = pd.read_csv(test_file)
df_stats = df.describe()
df_test_stats = df_test.describe()
#print df_stats
#print df_test_stats # Briefly investigate the dataset with basic statistics

In [6]:
df.describe()

,Variable_1,Variable_2,Variable_3,Variable_4,Variable_5,Variable_6,Variable_7,Variable_8,Variable_9,Variable_10,...,Variable_182,Variable_183,Variable_184,Variable_185,Variable_186,Variable_187,Variable_188,Variable_189,Variable_190,Labels
count,26699.000000,885.000000,940.000000,25670.000000,493.000000,733.000000,425.000000,732.000000,2240.000000,425.000000,...,733.000000,940.000000,733.000000,0,25670.000000,27017.000000,425.000000,27017.000000,641.000000,30000.000000
mean,1352.606839,51299.979661,36308.237234,61.396806,452684.835822,14.717599,8.602353,8.633880,44775.071464,13.157647,...,4.120055,7.570213,4.641201,NaN,296551.224581,0.711589,3678433.157647,38.917644,376203.359599,0.071867
std,3115.525869,194984.650107,150130.775262,146.588931,860834.855506,33.793865,23.429430,2.734459,72309.580554,46.586662,...,11.523167,38.936479,10.825531,NaN,662880.877648,2.962133,3718127.877525,101.055389,659739.367123,0.258271
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,24.000000,0.000000,0.000000,0.000000,8.000000,2994.760000,0.000000,...,0.000000,0.000000,0.000000,NaN,0.000000,0.000000,160657.000000,10.000000,0.000000,0.000000
50%,220.000000,0.000000,0.000000,32.000000,162864.900000,0.000000,2.000000,8.000000,10685.800000,4.000000,...,0.000000,0.000000,0.000000,NaN,53679.500000,0.000000,2414951.000000,22.000000,154802.700000,0.000000
75%,1340.000000,10806.000000,0.000000,56.000000,551520.000000,16.000000,10.000000,8.000000,50807.440000,14.000000,...,4.000000,0.000000,0.000000,NaN,419142.500000,0.000000,6472459.000000,42.000000,519039.000000,0.000000
max,124445.000000,3637080.000000,2274345.000000,7456.000000,5443200.000000,428.000000,378.000000,32.000000,343804.000000,878.000000,...,212.000000,948.000000,99.000000,NaN,16934400.000000,60.000000,13900000.000000,4862.000000,5443200.000000,1.000000

In [15]:
df[:1].drop(['Customer ID', 'Labels'], axis = 1).describe()

,Variable_1,Variable_2,Variable_3,Variable_4,Variable_5,Variable_6,Variable_7,Variable_8,Variable_9,Variable_10,...,Variable_181,Variable_182,Variable_183,Variable_184,Variable_185,Variable_186,Variable_187,Variable_188,Variable_189,Variable_190
count,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,1,0
mean,1780,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,604800,0,NaN,20,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1780,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,604800,0,NaN,20,NaN
25%,1780,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,604800,0,NaN,20,NaN
50%,1780,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,604800,0,NaN,20,NaN
75%,1780,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,604800,0,NaN,20,NaN
max,1780,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,604800,0,NaN,20,NaN

In [20]:
pd.DataFrame(df[:1].values.flatten())

            0
0         TR1
1        1780
2         NaN
3         NaN
4          16
5         NaN
6         NaN
7         NaN
8         NaN
9         NaN
10        NaN
11        NaN
12    7355320
13        NaN
14        NaN
15          0
16        NaN
17        NaN
18        NaN
19   226859.2
20        NaN
21        NaN
22        NaN
23         56
24        NaN
25        NaN
26        NaN
27        NaN
28        NaN
29        NaN
..        ...
162       NaN
163       NaN
164       NaN
165       NaN
166         7
167       NaN
168       NaN
169       NaN
170       NaN
171       NaN
172       NaN
173       NaN
174       NaN
175       NaN
176       NaN
177       NaN
178       NaN
179       NaN
180       NaN
181       NaN
182       NaN
183       NaN
184       NaN
185       NaN
186    604800
187         0
188       NaN
189        20
190       NaN
191         0

[192 rows x 1 columns]

In [21]:
pd.DataFrame(df[:1].drop(['Customer ID', 'Labels'], axis = 1).values.flatten()).describe()

                    0
count       40.000000
mean    413808.638675
std    1305052.816134
min        -20.000000
25%          0.785249
50%         58.000000
75%       1522.000000
max    7355320.000000

In [56]:
x=df[:1]

In [58]:
pd.DataFrame(pd.DataFrame(x.values.flatten()).describe().values.T)

    0              1               2   3         4   5     6        7
0  40  413808.638675  1305052.816134 -20  0.785249  58  1522  7355320

In [60]:
pd.DataFrame(pd.DataFrame(x.values.flatten()).describe().values.T)

    0              1               2   3         4   5     6        7
0  40  413808.638675  1305052.816134 -20  0.785249  58  1522  7355320

In [42]:
stats = pd.DataFrame(df[:1].values.flatten()).describe()

In [51]:
pd.DataFrame(stats.values.T,columns=[1,2,3,4,5,6,7,8])

    1              2               3   4         5   6     7        8
0  40  413808.638675  1305052.816134 -20  0.785249  58  1522  7355320

In [12]:
df = df[:8]#.drop(['Customer ID', 'Labels'], axis=1)
reload(dp)
test_obj = dp.engineer_feature(df)

In [13]:
test_obj.pd_feature()

(2,)
(2,)
(2,)
(2,)
(2,)
(2,)
(2,)
(2,)
0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
dtype: int64

In [64]:
np.sum([1,2,3,4])

10

In [38]:
clns = ['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']

In [39]:
clns

['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']

In [10]:
test = df.applymap(lambda x: 1 if x>0.5 else 0)

In [12]:
test.mean()

test    0.5
dtype: float64

In [13]:
df.mean()

test    0.4
dtype: float64

In [4]:
arr = np.array([1,0,1,1,0,0,0])

In [6]:
arr.astype(bool)

array([ True, False,  True,  True, False, False, False], dtype=bool)

In [3]:
arr = np.array([0.8, 0.9, 0.1, 0.3, 0.2, 0.5, 0.95])

In [4]:
idx = np.argsort(-arr)

In [5]:
idx

array([6, 1, 0, 5, 3, 4, 2])

In [6]:
length = 3

In [7]:
idx_pos = idx[:length]

In [8]:
idx_neg = idx[length:]

In [9]:
idx_pos

array([6, 1, 0])

In [10]:
idx_neg

array([5, 3, 4, 2])

In [12]:
arr[idx_pos] = 1

In [13]:
arr[idx_neg] = 0

In [14]:
arr

array([ 1.,  1.,  0.,  0.,  0.,  0.,  1.])

In [18]:
type(df_stats)

pandas.core.frame.DataFrame

In [38]:
df_tmp = df_stats[:1] == 0
df_tmp

,Variable_1,Variable_2,Variable_3,Variable_4,Variable_5,Variable_6,Variable_7,Variable_8,Variable_9,Variable_10,...,Variable_182,Variable_183,Variable_184,Variable_185,Variable_186,Variable_187,Variable_188,Variable_189,Variable_190,Labels
count,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False

In [40]:
header = df_tmp.columns.values

In [45]:
header

array(['Variable_1', 'Variable_2', 'Variable_3', 'Variable_4',
       'Variable_5', 'Variable_6', 'Variable_7', 'Variable_8',
       'Variable_9', 'Variable_10', 'Variable_11', 'Variable_12',
       'Variable_13', 'Variable_14', 'Variable_15', 'Variable_16',
       'Variable_17', 'Variable_18', 'Variable_19', 'Variable_20',
       'Variable_21', 'Variable_22', 'Variable_23', 'Variable_24',
       'Variable_25', 'Variable_26', 'Variable_27', 'Variable_28',
       'Variable_29', 'Variable_30', 'Variable_31', 'Variable_32',
       'Variable_33', 'Variable_34', 'Variable_35', 'Variable_36',
       'Variable_37', 'Variable_38', 'Variable_39', 'Variable_40',
       'Variable_41', 'Variable_42', 'Variable_43', 'Variable_44',
       'Variable_45', 'Variable_46', 'Variable_47', 'Variable_48',
       'Variable_49', 'Variable_50', 'Variable_51', 'Variable_52',
       'Variable_53', 'Variable_54', 'Variable_55', 'Variable_56',
       'Variable_57', 'Variable_58', 'Variable_59', 'Variable_60',
       'Variable_61', 'Variable_62', 'Variable_63', 'Variable_64',
       'Variable_65', 'Variable_66', 'Variable_67', 'Variable_68',
       'Variable_69', 'Variable_70', 'Variable_71', 'Variable_72',
       'Variable_73', 'Variable_74', 'Variable_75', 'Variable_76',
       'Variable_77', 'Variable_78', 'Variable_79', 'Variable_80',
       'Variable_81', 'Variable_82', 'Variable_83', 'Variable_84',
       'Variable_85', 'Variable_86', 'Variable_87', 'Variable_88',
       'Variable_89', 'Variable_90', 'Variable_91', 'Variable_92',
       'Variable_93', 'Variable_94', 'Variable_95', 'Variable_96',
       'Variable_97', 'Variable_98', 'Variable_99', 'Variable_100',
       'Variable_101', 'Variable_102', 'Variable_103', 'Variable_104',
       'Variable_105', 'Variable_106', 'Variable_107', 'Variable_108',
       'Variable_109', 'Variable_110', 'Variable_111', 'Variable_112',
       'Variable_113', 'Variable_114', 'Variable_115', 'Variable_116',
       'Variable_117', 'Variable_118', 'Variable_119', 'Variable_120',
       'Variable_121', 'Variable_122', 'Variable_123', 'Variable_124',
       'Variable_125', 'Variable_126', 'Variable_127', 'Variable_128',
       'Variable_129', 'Variable_130', 'Variable_131', 'Variable_132',
       'Variable_133', 'Variable_134', 'Variable_135', 'Variable_136',
       'Variable_137', 'Variable_138', 'Variable_139', 'Variable_140',
       'Variable_141', 'Variable_142', 'Variable_143', 'Variable_144',
       'Variable_145', 'Variable_146', 'Variable_147', 'Variable_148',
       'Variable_149', 'Variable_150', 'Variable_151', 'Variable_152',
       'Variable_153', 'Variable_154', 'Variable_155', 'Variable_156',
       'Variable_157', 'Variable_158', 'Variable_159', 'Variable_160',
       'Variable_161', 'Variable_162', 'Variable_163', 'Variable_164',
       'Variable_165', 'Variable_166', 'Variable_167', 'Variable_168',
       'Variable_169', 'Variable_170', 'Variable_171', 'Variable_172',
       'Variable_173', 'Variable_174', 'Variable_175', 'Variable_176',
       'Variable_177', 'Variable_178', 'Variable_179', 'Variable_180',
       'Variable_181', 'Variable_182', 'Variable_183', 'Variable_184',
       'Variable_185', 'Variable_186', 'Variable_187', 'Variable_188',
       'Variable_189', 'Variable_190', 'Labels'], dtype=object)

In [36]:
df_stats[:1]['Variable_31']

count    493
Name: Variable_31, dtype: float64

In [24]:
(df_stats[:1]==0).values

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False,  True, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True, False,  True,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True, False,
        False, False,  True, False, False, False, False, False,  True,
        False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True, False,
         True, False, False, False,  True, False, False, False, False,
        False, False]], dtype=bool)

In [41]:
header[(df_stats[:1]==0).values.flatten()]

array(['Variable_32', 'Variable_41', 'Variable_42', 'Variable_45',
       'Variable_53', 'Variable_84', 'Variable_110', 'Variable_124',
       'Variable_126', 'Variable_152', 'Variable_156', 'Variable_162',
       'Variable_171', 'Variable_179', 'Variable_181', 'Variable_185'], dtype=object)

In [32]:
df_test.columns.values[(df_test_stats[:1]==0).values.flatten()]

array(['Variable_31', 'Variable_40', 'Variable_41', 'Variable_44',
       'Variable_52', 'Variable_83', 'Variable_109', 'Variable_123',
       'Variable_125', 'Variable_151', 'Variable_155', 'Variable_161',
       'Variable_170', 'Variable_178', 'Variable_180', 'Variable_184'], dtype=object)

In [43]:
header_test = header[(df_test_stats[:1]==0).values.flatten()]
header_test

array(['Variable_32', 'Variable_41', 'Variable_42', 'Variable_45',
       'Variable_53', 'Variable_84', 'Variable_110', 'Variable_124',
       'Variable_126', 'Variable_152', 'Variable_156', 'Variable_162',
       'Variable_171', 'Variable_179', 'Variable_181', 'Variable_185'], dtype=object)

In [49]:
idx_invert = np.invert((df_stats[:1]==0).values.flatten())

In [52]:
header_non_null = header[idx_invert]

In [61]:
df_new = pd.DataFrame(df_stats[header_non_null][:1].values.flatten(), columns=['count'])

In [62]:
df_new.describe()

              count
count    175.000000
mean    6933.457143
std    11136.570983
min       96.000000
25%      493.000000
50%      733.000000
75%     1590.000000
max    30000.000000

In [44]:
df[header_test]

,Variable_32,Variable_41,Variable_42,Variable_45,Variable_53,Variable_84,Variable_110,Variable_124,Variable_126,Variable_152,Variable_156,Variable_162,Variable_171,Variable_179,Variable_181,Variable_185
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29973,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29978,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29979,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df=df.drop(['Labels'], axis=1)

In [10]:
df_test=df_test.drop(['Labels'], axis=1)

In [11]:
frames=[df,df_test]

In [12]:
df = pd.concat(frames, keys=['x', 'y'])

In [24]:
df_2 = df.applymap(lambda x: 0 if pd.isnull(x) else 1)

In [28]:
header = df.columns.values.flatten()

In [31]:
df.ix['x']

,Customer ID,Variable_1,Variable_2,Variable_3,Variable_4,Variable_5,Variable_6,Variable_7,Variable_8,Variable_9,...,Variable_181,Variable_182,Variable_183,Variable_184,Variable_185,Variable_186,Variable_187,Variable_188,Variable_189,Variable_190
0,TR1,1780,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,604800,0,NaN,20,NaN
1,TR2,1625,NaN,NaN,120,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,77819,0,NaN,40,NaN
2,TR3,160,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,34,NaN
3,TR4,135,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,20,NaN
4,TR5,45,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,604800,0,NaN,12,NaN
5,TR6,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,TR7,0,NaN,NaN,56,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,359324,0,NaN,22,NaN
7,TR8,385,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,13699,0,NaN,16,NaN
8,TR9,NaN,NaN,NaN,NaN,NaN,16,NaN,16,NaN,...,NaN,4,NaN,18,NaN,NaN,NaN,NaN,NaN,NaN
9,TR10,0,NaN,NaN,216,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,207081,0,NaN,78,NaN
10,TR11,0,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,256669,0,NaN,14,NaN
11,TR12,0,NaN,NaN,8,NaN,NaN,NaN,NaN,2777.44,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,16,NaN
12,TR13,795,NaN,NaN,112,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,195335,0,NaN,44,NaN
13,TR14,660,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,6,NaN
14,TR15,1845,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,30,NaN
15,TR16,225,NaN,NaN,112,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,381878,0,NaN,60,NaN
16,TR17,850,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,97587,0,NaN,44,NaN
17,TR18,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,TR19,1100,NaN,NaN,88,NaN,NaN,NaN,NaN,270413.60,...,NaN,NaN,NaN,NaN,NaN,269213,5,NaN,48,NaN
19,TR20,50,NaN,NaN,40,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,68103,0,NaN,14,NaN
20,TR21,410,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1663312,10,NaN,18,NaN
21,TR22,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0,NaN
22,TR23,4685,NaN,NaN,168,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,496440,0,NaN,64,NaN
23,TR24,870,NaN,NaN,136,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,322483,0,NaN,102,NaN
24,TR25,0,NaN,NaN,56,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,825125,0,NaN,44,NaN
25,TR26,1245,NaN,NaN,472,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,352975,5,NaN,206,NaN
26,TR27,245,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,30,NaN
27,TR28,2075,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,0,NaN
28,TR29,80,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,4,NaN
29,TR30,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29970,TR29971,90,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,24773,0,NaN,74,NaN
29971,TR29972,5240,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,12,NaN
29972,TR29973,4825,NaN,NaN,56,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,41517,10,NaN,34,NaN
29973,TR29974,0,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,5,NaN,6,NaN
29974,TR29975,625,NaN,NaN,8,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,2,NaN
29975,TR29976,245,NaN,NaN,80,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,214039,0,NaN,20,NaN
29976,TR29977,0,NaN,NaN,40,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1108877,0,NaN,28,NaN
29977,TR29978,0,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,12,NaN
29978,TR29979,80,NaN,NaN,56,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3493,0,NaN,56,NaN
29979,TR29980,210,NaN,NaN,112,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,180397,0,NaN,76,NaN
29980,TR29981,0,NaN,NaN,40,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,36,NaN
29981,TR29982,1525,NaN,NaN,136,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,127974,0,NaN,160,NaN
29982,TR29983,3690,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,4,NaN
29983,TR29984,35,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,22,NaN
29984,TR29985,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3628800,NaN,NaN
29985,TR29986,1855,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,116340,0,NaN,26,NaN
29986,TR29987,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN
29987,TR29988,80,NaN,NaN,40,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,269913,0,NaN,10,NaN
29988,TR29989,1390,NaN,NaN,112,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,138677,0,NaN,72,NaN
29989,TR29990,0,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4233600,0,NaN,16,NaN
29990,TR29991,2590,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,2,NaN
29991,TR29992,0,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,983941,0,NaN,0,NaN
29992,TR29993,180,NaN,NaN,40,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,14,NaN
29993,TR29994,2580,NaN,NaN,48,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2418766,0,NaN,54,NaN
29994,TR29995,415,NaN,NaN,48,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,12,NaN
29995,TR29996,90,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,554421,5,NaN,26,NaN
29996,TR29997,6275,NaN,NaN,56,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,665525,10,NaN,86,NaN
29997,TR29998,17210,NaN,NaN,200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,109788,0,NaN,102,NaN
29998,TR29999,30,NaN,NaN,32,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,0,NaN,42,NaN
29999,TR30000,2520,NaN,NaN,328,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,339374,0,NaN,36,NaN

In [25]:
df_2

         Customer ID  Variable_1  Variable_2  Variable_3  Variable_4  \
x 0                1           1           0           0           1
  1                1           1           0           0           1
  2                1           1           0           0           1
  3                1           1           0           0           1
  4                1           1           0           0           1
  5                1           0           1           0           0
  6                1           1           0           0           1
  7                1           1           0           0           1
  8                1           0           0           0           0
  9                1           1           0           0           1
  10               1           1           0           0           1
  11               1           1           0           0           1
  12               1           1           0           0           1
  13               1           1           0           0           1
  14               1           1           0           0           1
  15               1           1           0           0           1
  16               1           1           0           0           1
  17               1           0           0           1           0
  18               1           1           0           0           1
  19               1           1           0           0           1
  20               1           1           0           0           1
  21               1           1           0           0           0
  22               1           1           0           0           1
  23               1           1           0           0           1
  24               1           1           0           0           1
  25               1           1           0           0           1
  26               1           1           0           0           1
  27               1           1           0           0           1
  28               1           1           0           0           1
  29               1           0           0           1           0
...              ...         ...         ...         ...         ...
y 19970            1           1           0           0           1
  19971            1           1           0           0           1
  19972            1           1           0           0           1
  19973            1           1           0           0           0
  19974            1           1           0           0           1
  19975            1           1           0           0           1
  19976            1           1           0           0           1
  19977            1           1           0           0           1
  19978            1           0           1           0           0
  19979            1           1           0           0           1
  19980            1           1           0           0           1
  19981            1           1           0           0           1
  19982            1           1           0           0           1
  19983            1           1           0           0           1
  19984            1           1           0           0           0
  19985            1           1           0           0           1
  19986            1           0           0           0           0
  19987            1           1           0           0           1
  19988            1           1           0           0           1
  19989            1           1           0           0           1
  19990            1           1           0           0           1
  19991            1           0           0           0           0
  19992            1           1           0           0           1
  19993            1           0           0           0           1
  19994            1           1           0           0           1
  19995            1           1           0           0           1
  19996            1           1           0           0           1
  19997            1           1           0           0           1
  19998            1           1           0           0           1
  19999            1           1           0           0           1

         Variable_5  Variable_6  Variable_7  Variable_8  Variable_9  \
x 0               0           0           0           0           0
  1               0           0           0           0           0
  2               0           0           0           0           0
  3               0           0           0           0           0
  4               0           0           0           0           0
  5               0           0           0           0           0
  6               0           0           0           0           0
  7               0           0           0           0           0
  8               0           1           0           1           0
  9               0           0           0           0           0
  10              0           0           0           0           0
  11              0           0           0           0           1
  12              0           0           0           0           0
  13              0           0           0           0           0
  14              0           0           0           0           0
  15              0           0           0           0           0
  16              0           0           0           0           0
  17              0           0           0           0           0
  18              0           0           0           0           1
  19              0           0           0           0           0
  20              0           0           0           0           0
  21              0           0           0           0           0
  22              0           0           0           0           0
  23              0           0           0           0           0
  24              0           0           0           0           0
  25              0           0           0           0           0
  26              0           0           0           0           0
  27              0           0           0           0           0
  28              0           0           0           0           0
  29              0           0           0           0           0
...             ...         ...         ...         ...         ...
y 19970           0           0           0           0           1
  19971           0           0           0           0           0
  19972           0           0           0           0           1
  19973           0           0           0           0           0
  19974           0           0           0           0           0
  19975           0           0           0           0           0
  19976           0           0           0           0           0
  19977           0           0           0           0           0
  19978           0           0           0           0           0
  19979           0           0           0           0           0
  19980           0           0           0           0           0
  19981           0           0           0           0           0
  19982           0           0           0           0           0
  19983           0           0           0           0           1
  19984           0           0           0           0           0
  19985           0           0           0           0           0
  19986           0           0           1           0           0
  19987           0           0           0           0           0
  19988           0           0           0           0           0
  19989           0           0           0           0           0
  19990           0           0           0           0           0
  19991           0           0           1           0           0
  19992           0           0           0           0           0
  19993           0           0           0           0           0
  19994           0           0           0           0           0
  19995           0           0           0           0           0
  19996           0           0           0           0           0
  19997           0           0           0           0           0
  19998           0           0           0           0           0
  19999           0           0           0           0           1

             ...       Variable_181  Variable_182  Variable_183  Variable_184  \
x 0          ...                  0             0             0             0
  1          ...                  0             0             0             0
  2          ...                  0             0             0             0
  3          ...                  0             0             0             0
  4          ...                  0             0             0             0
  5          ...                  0             0             0             0
  6          ...                  0             0             0             0
  7          ...                  0             0             0             0
  8          ...                  0             1             0             1
  9          ...                  0             0             0             0
  10         ...                  0             0             0             0
  11         ...                  0             0             0             0
  12         ...                  0             0             0             0
  13         ...                  0             0             0             0
  14         ...                  0             0             0             0
  15         ...                  0             0             0             0
  16         ...                  0             0             0             0
  17         ...                  0             0             1             0
  18         ...                  0             0             0             0
  19         ...                  0             0             0             0
  20         ...                  0             0             0             0
  21         ...                  0             0             0             0
  22         ...                  0             0             0             0
  23         ...                  0             0             0             0
  24         ...                  0             0             0             0
  25         ...                  0             0             0             0
  26         ...                  0             0             0             0
  27         ...                  0             0             0             0
  28         ...                  0             0             0             0
  29         ...                  0             0             1             0
...          ...                ...           ...           ...           ...
y 19970      ...                  0             0             0             0
  19971      ...                  0             0             0             0
  19972      ...                  0             0             0             0
  19973      ...                  0             0             0             0
  19974      ...                  0             0             0             0
  19975      ...                  0             0             0             0
  19976      ...                  0             0             0             0
  19977      ...                  0             0             0             0
  19978      ...                  0             0             0             0
  19979      ...                  0             0             0             0
  19980      ...                  0             0             0             0
  19981      ...                  0             0             0             0
  19982      ...                  0             0             0             0
  19983      ...                  0             0             0             0
  19984      ...                  0             0             0             0
  19985      ...                  0             0             0             0
  19986      ...                  0             0             0             0
  19987      ...                  0             0             0             0
  19988      ...                  0             0             0             0
  19989      ...                  0             0             0             0
  19990      ...                  0             0             0             0
  19991      ...                  0             0             0             0
  19992      ...                  0             0             0             0
  19993      ...                  0             0             0             0
  19994      ...                  0             0             0             0
  19995      ...                  0             0             0             0
  19996      ...                  0             0             0             0
  19997      ...                  0             0             0             0
  19998      ...                  0             0             0             0
  19999      ...                  0             0             0             0

         Variable_185  Variable_186  Variable_187  Variable_188  Variable_189  \
x 0                 0             1             1             0             1
  1                 0             1             1             0             1
  2                 0             1             1             0             1
  3                 0             1             1             0             1
  4                 0             1             1             0             1
  5                 0             0             0             0             0
  6                 0             1             1             0             1
  7                 0             1             1             0             1
  8                 0             0             0             0             0
  9                 0             1             1             0             1
  10                0             1             1             0             1
  11                0             1             1             0             1
  12                0             1             1             0             1
  13                0             1             1             0             1
  14                0             1             1             0             1
  15                0             1             1             0             1
  16                0             1             1             0             1
  17                0             0             0             0             0
  18                0             1             1             0             1
  19                0             1             1             0             1
  20                0             1             1             0             1
  21                0             0             1             0             1
  22                0             1             1             0             1
  23                0             1             1             0             1
  24                0             1             1             0             1
  25                0             1             1             0             1
  26                0             1             1             0             1
  27                0             1             1             0             1
  28                0             1             1             0             1
  29                0             0             0             0             0
...               ...           ...           ...           ...           ...
y 19970             0             1             1             0             1
  19971             0             1             1             0             1
  19972             0             1             1             0             1
  19973             0             0             1             0             1
  19974             0             1             1             0             1
  19975             0             1             1             0             1
  19976             0             1             1             0             1
  19977             0             1             1             0             1
  19978             0             0             0             0             0
  19979             0             1             1             0             1
  19980             0             1             1             0             1
  19981             0             1             1             0             1
  19982             0             1             1             0             1
  19983             0             1             1             0             1
  19984             0             0             1             0             1
  19985             0             1             1             0             1
  19986             0             0             0             1             0
  19987             0             1             1             0             1
  19988             0             1             1             0             1
  19989             0             1             1             0             1
  19990             0             1             1             0             1
  19991             0             0             0             1             0
  19992             0             1             1             0             1
  19993             0             1             1             0             1
  19994             0             1             1             0             1
  19995             0             1             1             0             1
  19996             0             1             1             0             1
  19997             0             1             1             0             1
  19998             0             1             1             0             1
  19999             0             1             1             0             1

         Variable_190
x 0                 0
  1                 0
  2                 0
  3                 0
  4                 0
  5                 0
  6                 0
  7                 0
  8                 0
  9                 0
  10                0
  11                0
  12                0
  13                0
  14                0
  15                0
  16                0
  17                0
  18                0
  19                0
  20                0
  21                0
  22                0
  23                0
  24                0
  25                0
  26                0
  27                0
  28                0
  29                1
...               ...
y 19970             0
  19971             0
  19972             0
  19973             0
  19974             0
  19975             0
  19976             0
  19977             0
  19978             0
  19979             0
  19980             0
  19981             0
  19982             0
  19983             0
  19984             0
  19985             0
  19986             0
  19987             0
  19988             0
  19989             0
  19990             0
  19991             0
  19992             0
  19993             0
  19994             0
  19995             0
  19996             0
  19997             0
  19998             0
  19999             0

[50000 rows x 191 columns]